### ISSUE TITLE
Add ARRAY(SELECT) example to the arrays file

### ISSUE THREAD

**Issue by polobo** [cybertec-postgresql/postgres-showcase#4]
SELECT ARRAY(SELECT col1 FROM ( VALUES (1), (2), (3) ) vals (v)); -- {1,2,3}

basically equivalent to SELECT (SELECT array_agg(col1) ...)

I'm not sure whether one performs better than the other but the ARRAY() form seems more natural when working in a scalar subquery context.

**Comment by kmoppel** [comment]
Added with minor corrections. Feel free to do a PR when not exactly what you meant:)

-- using the ARRAY constructor
SELECT ARRAY(VALUES (1), (2), (3));
-- ARRAY constructor with a subselect
SELECT ARRAY(SELECT v FROM ( VALUES (1), (2), (3) ) vals (v));
