### ISSUE TITLE
Extract the run command into a script.

### ISSUE THREAD

**Issue by RobertZenz** [cybertec-postgresql/postgres-showcase#5]
The run command mentioned in the README should be extracted into a script so that someone can simply clone the repository and run the script, instead of copying a command.

It can also be shortened, depending on how portable one does want it. For example this is the shortest incarnation I can come up with:

    ls -v *.sql | xargs psql -f

However, the `-v` flag of `ls` is not portable and is most likely only available in the GNU version...but so is the `-V` flag of `sort`, as far as I am aware. So the most portable script is most likely this one:

    ls *.sql | sort -n | xargs psql -f

**Comment by kmoppel** [comment]
A good idea! Could make it more easier for beginners. So I've added a rollout.sh script + changed the SQL scripts so that they could be executed also one by one (added \c + set role)
